"use client";
import { api } from "@/lib/api"; import { usePoll } from "@/lib/usePoll";
import { StatusBar } from "@/components/StatusBar"; import { TickStrip } from "@/components/TickStrip"; import { BiometricsStrip } from "@/components/BiometricsStrip"; import { DecisionFeed } from "@/components/DecisionFeed"; import { EpisodeTimeline } from "@/components/EpisodeTimeline"; import { ScoresPanel } from "@/components/ScoresPanel"; import { MemoryPanel,SevenDayPanel } from "@/components/MemoryPanels";
import { CapturePanel } from "@/components/CapturePanel";
export default function Dashboard(){
 const status=usePoll(api.status,1000),ticks=usePoll(()=>api.ticks(30),1000),decisions=usePoll(()=>api.decisions(50),1000);
 const episodes=usePoll(()=>api.episodes(),5000),scores=usePoll(()=>api.scores("daily"),5000),seeded=usePoll(()=>api.seeded(7),5000);
 const summary=usePoll(api.summaryToday,5000),pending=usePoll(api.pendingChecks,5000); const isMock=[status,ticks,decisions,episodes,scores,seeded,summary,pending].some(x=>x.mock);
 return <main className="mx-auto max-w-[1800px] p-3 lg:p-5">{isMock&&<div className="mb-3 rounded-md border border-amber-500/30 bg-amber-500/10 px-4 py-2 text-xs font-semibold text-amber-200">API offline — mock data</div>}<StatusBar status={status.data}/><CapturePanel status={status.data}/><div className="mt-3"><TickStrip ticks={ticks.data}/></div><div className="mt-3"><BiometricsStrip/></div><div className="mt-3 grid items-start gap-3 xl:grid-cols-[minmax(0,1.65fr)_minmax(300px,.75fr)_minmax(320px,.85fr)]"><div className="space-y-3"><DecisionFeed decisions={decisions.data}/><EpisodeTimeline episodes={episodes.data}/></div><div className="space-y-3"><MemoryPanel summary={summary.data} pending={pending.data}/><SevenDayPanel rows={seeded.data}/></div><ScoresPanel scores={scores.data}/></div><footer className="py-4 text-center text-[10px] uppercase tracking-[.2em] text-zinc-700">Always writes · rarely speaks · never queues</footer></main>}
