import {
  Armchair,
  Baby,
  BedDouble,
  Brain,
  CalendarPlus,
  Car,
  Cigarette,
  CircleHelp,
  Coffee,
  Dumbbell,
  Flame,
  HeartPulse,
  Leaf,
  Monitor,
  Moon,
  Pill,
  Plane,
  Smartphone,
  Snowflake,
  Sofa,
  Sun,
  Sunrise,
  Sunset,
  Syringe,
  Target,
  Trees,
  Users,
  Utensils,
  UtensilsCrossed,
  Volume2,
  Wine,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { Glyph } from "@/lib/calendar";

export const GLYPHS: Record<Glyph, LucideIcon> = {
  coffee: Coffee,
  tea: Leaf,
  energy: Zap,
  meal: Utensils,
  "no-meal": UtensilsCrossed,
  wine: Wine,
  nicotine: Cigarette,
  workout: Dumbbell,
  sun: Sun,
  shade: Trees,
  seated: Armchair,
  phone: Smartphone,
  computer: Monitor,
  bed: BedDouble,
  people: Users,
  nap: Sofa,
  sauna: Flame,
  cold: Snowflake,
  peptide: Syringe,
  pill: Pill,
  car: Car,
  plane: Plane,
  stress: HeartPulse,
  mind: Brain,
  whisper: Volume2,
  ask: CircleHelp,
  act: CalendarPlus,
  baby: Baby,
  moon: Moon,
  sunrise: Sunrise,
  sunset: Sunset,
  target: Target,
};
