// Protocol library: seeded templates for the "Use this protocol" guided review.
// Every item is a toggle before it lands in My protocol.
// Never a dose amount anywhere. Where a dose exists, clinicianDose is true and
// the UI reads "dose set by your clinician".

import type {
  Anchored,
  ProtocolItemTemplate,
  ProtocolTemplate,
  Weekday,
  Window,
} from "./types";

// 0 = Monday.
export const ALL_DAYS: Weekday[] = [0, 1, 2, 3, 4, 5, 6];
export const WEEKDAY_LABELS: Record<Weekday, string> = {
  0: "Mon",
  1: "Tue",
  2: "Wed",
  3: "Thu",
  4: "Fri",
  5: "Sat",
  6: "Sun",
};

export const CLINICIAN_DOSE_LINE = "dose set by your clinician";

export function isAnchored(window: Window | Anchored): window is Anchored {
  return "anchor" in window;
}

// Sleep first and New parent share the same clock windows.
const sleepFirstItems = (prefix: string): ProtocolItemTemplate[] => [
  {
    id: `${prefix}-bed`,
    name: "Bed",
    kind: "sleep",
    window: { start: "22:30", end: "06:30" },
    days: ALL_DAYS,
    verify: "none",
    clinicianDose: false,
    note: "lights out 22:30",
  },
  {
    id: `${prefix}-wake`,
    name: "Up by 06:30",
    kind: "light",
    window: { start: "06:00", end: "06:30" },
    days: ALL_DAYS,
    verify: "none",
    clinicianDose: false,
    note: "daylight on waking",
  },
  {
    id: `${prefix}-caffeine`,
    name: "Caffeine",
    kind: "hydration",
    window: { start: "06:30", end: "13:30" },
    days: ALL_DAYS,
    verify: "none",
    clinicianDose: false,
    note: "last caffeine by 13:30",
  },
  {
    id: `${prefix}-screens`,
    name: "Screens off",
    kind: "screens",
    window: { start: "21:30", end: "22:30" },
    days: ALL_DAYS,
    verify: "none",
    clinicianDose: false,
    note: "screens off from 21:30",
  },
  {
    id: `${prefix}-exercise`,
    name: "Vigorous exercise",
    kind: "move",
    window: { start: "06:30", end: "18:30" },
    days: ALL_DAYS,
    verify: "none",
    clinicianDose: false,
    note: "finish vigorous exercise by 18:30",
  },
  {
    id: `${prefix}-last-meal`,
    name: "Last meal",
    kind: "meal",
    window: { start: "18:00", end: "19:00" },
    days: ALL_DAYS,
    verify: "none",
    clinicianDose: false,
    note: "done eating by 19:00",
  },
];

export const PROTOCOLS: ProtocolTemplate[] = [
  {
    id: "blueprint",
    name: "Blueprint",
    chip: "Extreme",
    tint: "sand",
    icon: "protocol",
    line: "Bryan's day, as published. Early, fixed, and full.",
    chips: ["Wake 05:00", "Bed 20:30", "No caffeine", "No alcohol"],
    notes: ["No caffeine", "No alcohol"],
    items: [
      {
        id: "bp-wake-light",
        name: "Wake and bright light",
        kind: "light",
        window: { start: "05:00", end: "05:04" },
        days: ALL_DAYS,
        verify: "none",
        clinicianDose: false,
        note: "3 to 4 min of bright light on waking",
      },
      {
        id: "bp-exercise",
        name: "Exercise",
        kind: "move",
        window: { start: "06:00", end: "07:30" },
        days: [0, 1, 2, 3, 4, 5],
        verify: "none",
        clinicianDose: false,
        note: "3 strength and 3 cardio sessions a week",
      },
      {
        id: "bp-sauna",
        name: "Sauna",
        kind: "sauna",
        window: { start: "07:30", end: "07:50" },
        days: ALL_DAYS,
        verify: "none",
        clinicianDose: false,
        note: "20 min",
      },
      {
        id: "bp-red-light",
        name: "Red light",
        kind: "light",
        window: { start: "08:00", end: "08:10" },
        days: ALL_DAYS,
        verify: "none",
        clinicianDose: false,
        note: "after the sauna",
      },
      {
        id: "bp-meal-1",
        name: "First meal",
        kind: "meal",
        window: { start: "05:35", end: "06:00" },
        days: ALL_DAYS,
        verify: "none",
        clinicianDose: false,
        note: "with the morning stack",
      },
      {
        id: "bp-meal-2",
        name: "Second meal",
        kind: "meal",
        window: { start: "10:00", end: "10:30" },
        days: ALL_DAYS,
        verify: "none",
        clinicianDose: false,
      },
      {
        id: "bp-meal-3",
        name: "Third meal",
        kind: "meal",
        window: { start: "11:00", end: "11:30" },
        days: ALL_DAYS,
        verify: "none",
        clinicianDose: false,
      },
      {
        id: "bp-last-meal",
        name: "Last meal",
        kind: "meal",
        window: { start: "12:00", end: "12:30" },
        days: ALL_DAYS,
        verify: "none",
        clinicianDose: false,
        note: "nothing after 12:30",
      },
      {
        id: "bp-hydration-cutoff",
        name: "Hydration cutoff",
        kind: "hydration",
        window: { start: "05:00", end: "16:00" },
        days: ALL_DAYS,
        verify: "none",
        clinicianDose: false,
        note: "last fluids by 16:00",
      },
      {
        id: "bp-evening-walk",
        name: "Outdoor walk",
        kind: "move",
        window: { start: "19:30", end: "20:00" },
        days: ALL_DAYS,
        verify: "none",
        clinicianDose: false,
        note: "outside, easy pace",
      },
      {
        id: "bp-screens-off",
        name: "Screens off",
        kind: "screens",
        window: { start: "19:30", end: "20:30" },
        days: ALL_DAYS,
        verify: "none",
        clinicianDose: false,
        note: "screens off from 19:30",
      },
      {
        id: "bp-bed",
        name: "Bed",
        kind: "sleep",
        window: { start: "20:30", end: "05:00" },
        days: ALL_DAYS,
        verify: "none",
        clinicianDose: false,
        note: "lights out 20:30",
      },
      {
        id: "bp-supp-essentials",
        name: "Essentials",
        kind: "supplement",
        window: { start: "05:35", end: "06:00" },
        days: ALL_DAYS,
        verify: "pill_bottle",
        clinicianDose: false,
        note: "morning stack",
      },
      {
        id: "bp-supp-antioxidants",
        name: "Antioxidants",
        kind: "supplement",
        window: { start: "05:35", end: "06:00" },
        days: ALL_DAYS,
        verify: "pill_bottle",
        clinicianDose: false,
        note: "morning stack",
      },
      {
        id: "bp-supp-omega-3",
        name: "Omega-3",
        kind: "supplement",
        window: { start: "05:35", end: "06:00" },
        days: ALL_DAYS,
        verify: "pill_bottle",
        clinicianDose: false,
        note: "morning stack, with food",
      },
      {
        id: "bp-supp-nr-nmn",
        name: "NR/NMN",
        kind: "supplement",
        window: { start: "05:35", end: "06:00" },
        days: ALL_DAYS,
        verify: "pill_bottle",
        clinicianDose: false,
        note: "morning stack",
      },
    ],
    flags: {
      nightWakingsNeverRed: false,
      napsAnyTimeUnder20: false,
      ceilingsLabel: null,
      anchorToActualSleep: false,
    },
  },
  {
    id: "sleep-first",
    name: "Sleep first",
    chip: "Gentle",
    tint: "sage",
    icon: "sleep",
    line: "A fixed bed and wake time, and everything else keeps out of their way.",
    chips: ["Bed 22:30", "Up 06:30", "Caffeine until 13:30"],
    items: sleepFirstItems("sf"),
    flags: {
      nightWakingsNeverRed: false,
      napsAnyTimeUnder20: false,
      ceilingsLabel: null,
      anchorToActualSleep: false,
    },
  },
  {
    id: "new-parent",
    name: "New parent",
    chip: "Forgiving",
    tint: "bluegrey",
    icon: "people",
    line: "The same windows as Sleep first, scored for a life you do not control.",
    chips: ["No red for night wakings", "Naps under 20 min", "Ceilings not your decision"],
    items: [
      ...sleepFirstItems("np"),
      {
        id: "np-nap",
        name: "Nap",
        kind: "sleep",
        window: { start: "06:30", end: "22:30" },
        days: ALL_DAYS,
        verify: "none",
        clinicianDose: false,
        note: "any time, under 20 min",
      },
    ],
    flags: {
      nightWakingsNeverRed: true,
      napsAnyTimeUnder20: true,
      ceilingsLabel: "not your decision",
      anchorToActualSleep: false,
    },
  },
  {
    id: "glp1-companion",
    name: "GLP-1 companion",
    chip: "Weekly pen",
    tint: "slate",
    icon: "peptide",
    line: "The same pen day every week, with meals, water and movement around it.",
    chips: ["Pen on Monday", "Protein first", "Hydration target", "Move daily"],
    items: [
      {
        id: "glp-pen",
        name: "Weekly pen",
        kind: "dose",
        window: { start: "07:00", end: "10:00" },
        days: [0],
        cycle: { weekly: 0 },
        verify: "pen",
        clinicianDose: true,
        note: "same day each week",
      },
      {
        id: "glp-protein-meals",
        name: "Protein-first meals",
        kind: "meal",
        window: { start: "08:00", end: "19:00" },
        days: ALL_DAYS,
        verify: "none",
        clinicianDose: false,
        note: "protein first, inside the eating window",
      },
      {
        id: "glp-hydration",
        name: "Hydration target",
        kind: "hydration",
        window: { start: "07:00", end: "20:00" },
        days: ALL_DAYS,
        verify: "none",
        clinicianDose: false,
        note: "spread through the day",
      },
      {
        id: "glp-movement",
        name: "Movement daily",
        kind: "move",
        window: { start: "07:00", end: "20:00" },
        days: ALL_DAYS,
        verify: "none",
        clinicianDose: false,
        note: "any movement counts",
      },
    ],
    flags: {
      nightWakingsNeverRed: false,
      napsAnyTimeUnder20: false,
      ceilingsLabel: null,
      anchorToActualSleep: false,
    },
  },
  {
    id: "peptide-adherence",
    name: "Peptide adherence",
    chip: "Cycles",
    tint: "stone",
    icon: "peptide",
    line: "Morning and evening injection windows, weekly items, and an on and off calendar.",
    chips: ["Morning 07:00 to 10:00", "Evening 19:00 to 22:00", "28 days on, 14 off"],
    items: [
      {
        id: "pa-am-injection",
        name: "Morning injection",
        kind: "dose",
        window: { start: "07:00", end: "10:00" },
        days: ALL_DAYS,
        cycle: { onDays: 28, offDays: 14 },
        verify: "vial_syringe",
        clinicianDose: true,
        note: "on days only",
      },
      {
        id: "pa-pm-injection",
        name: "Evening injection",
        kind: "dose",
        window: { start: "19:00", end: "22:00" },
        days: ALL_DAYS,
        cycle: { onDays: 28, offDays: 14 },
        verify: "vial_syringe",
        clinicianDose: true,
        note: "on days only",
      },
      {
        id: "pa-weekly-injection",
        name: "Weekly injection",
        kind: "dose",
        window: { start: "07:00", end: "10:00" },
        days: [0],
        cycle: { weekly: 0 },
        verify: "vial_syringe",
        clinicianDose: true,
        note: "same day each week",
      },
      {
        id: "pa-weekly-vial-prep",
        name: "Weekly vial prep",
        kind: "dose",
        window: { start: "19:00", end: "22:00" },
        days: [6],
        cycle: { weekly: 6 },
        verify: "vial_syringe",
        clinicianDose: true,
        note: "reconstitute and label the vial",
      },
    ],
    flags: {
      nightWakingsNeverRed: false,
      napsAnyTimeUnder20: false,
      ceilingsLabel: null,
      anchorToActualSleep: false,
    },
  },
  {
    id: "shift-and-travel",
    name: "Shift and travel",
    chip: "Anchored",
    tint: "slate",
    icon: "watch",
    line: "Every window is measured from when you actually slept, not from the clock.",
    chips: ["Anchored to sleep", "Any time zone", "Any shift"],
    items: [
      {
        id: "st-wake-light",
        name: "Bright light on waking",
        kind: "light",
        window: { anchor: "wake", offsetMin: 0, lengthMin: 30 },
        days: ALL_DAYS,
        verify: "none",
        clinicianDose: false,
        note: "first 30 min after waking",
      },
      {
        id: "st-caffeine",
        name: "Caffeine",
        kind: "hydration",
        window: { anchor: "wake", offsetMin: 60, lengthMin: 420 },
        days: ALL_DAYS,
        verify: "none",
        clinicianDose: false,
        note: "from 1 h after waking, for 7 h",
      },
      {
        id: "st-move",
        name: "Move",
        kind: "move",
        window: { anchor: "bed", offsetMin: -720, lengthMin: 480 },
        days: ALL_DAYS,
        verify: "none",
        clinicianDose: false,
        note: "finish vigorous exercise 4 h before bed",
      },
      {
        id: "st-last-meal",
        name: "Last meal",
        kind: "meal",
        window: { anchor: "bed", offsetMin: -240, lengthMin: 60 },
        days: ALL_DAYS,
        verify: "none",
        clinicianDose: false,
        note: "3 to 4 h before bed",
      },
      {
        id: "st-screens",
        name: "Screens off",
        kind: "screens",
        window: { anchor: "bed", offsetMin: -60, lengthMin: 60 },
        days: ALL_DAYS,
        verify: "none",
        clinicianDose: false,
        note: "the hour before bed",
      },
      {
        id: "st-sleep",
        name: "Sleep",
        kind: "sleep",
        window: { anchor: "bed", offsetMin: 0, lengthMin: 480 },
        days: ALL_DAYS,
        verify: "none",
        clinicianDose: false,
        note: "whenever bed actually is",
      },
    ],
    flags: {
      nightWakingsNeverRed: false,
      napsAnyTimeUnder20: false,
      ceilingsLabel: null,
      anchorToActualSleep: true,
    },
  },
];

export function protocolById(id: string): ProtocolTemplate | undefined {
  return PROTOCOLS.find((p) => p.id === id);
}
