# shellcheck shell=bash
# Shared by new_tester.sh and remove_tester.sh. Sourced, not run.
set -euo pipefail

DEPLOY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$DEPLOY_DIR"

#: Built by the `backend-image` service in docker-compose.yml.
IMAGE="hackrice-backend:local"
#: The dashboard image is per tester (hackrice-dashboard:NAME): Next bakes
#: the /t/NAME/dashboard base path in at build time.
DASHBOARD_IMAGE="hackrice-dashboard"
#: Inside its container every backend listens on 8010 (so the dashboard finds
#: it at http://backend-NAME:8010). On the host, testers get 8101, 8102, ...
#: bound to 127.0.0.1 only: for curl on this machine; the world goes via Caddy.
BACKEND_PORT=8010
FIRST_PORT=8101
#: The unprivileged users the images run as: deploy/Dockerfile's `app`, and
#: node:alpine's `node` in dashboard/Dockerfile.
RUNTIME_UID=10001
DASHBOARD_UID=1000

die() { echo "error: $*" >&2; exit 1; }

compose() { docker compose "$@"; }

# Lower-case, digits and dashes: it becomes a URL segment, a compose service
# name and a DNS name on the compose network, and must be valid as all three.
valid_name() { [[ "$1" =~ ^[a-z][a-z0-9-]{0,30}$ ]]; }

# The last KEY=value in FILE, without sourcing it (a value may hold anything).
env_value() { sed -n "s/^$1=//p" "$2" | tail -n 1; }

need_env() {
  [ -f .env ] || die "deploy/.env is missing: cp .env.example .env and fill it in"
  DOMAIN="$(env_value DOMAIN .env)"
  [ -n "$DOMAIN" ] || die "DOMAIN is empty in deploy/.env"
}

# Rebuild docker-compose.override.yml from testers/*.yml. Compose loads the
# override next to docker-compose.yml by default, so `docker compose ...`
# always sees every tester without anyone listing files. Written to a temp
# file first so a half-written override never exists.
render_override() {
  local tmp files f
  tmp="$(mktemp "$DEPLOY_DIR/.override.XXXXXX")"
  files=(testers/*.yml)
  {
    echo "# GENERATED by new_tester.sh / remove_tester.sh from testers/*.yml."
    echo "# Do not edit: the next add or remove rewrites it."
    if [ -e "${files[0]}" ]; then
      echo "services:"
      # Each testers/NAME.yml starts with its own `services:` line; skip it.
      for f in "${files[@]}"; do tail -n +2 "$f"; done
    else
      echo "services: {}"
    fi
  } > "$tmp"
  mv "$tmp" docker-compose.override.yml
}

# Ask a running Caddy to re-read its routes. A reload keeps serving the old
# config until the new one is valid, and `stream_close_delay` in each route
# keeps the other testers' glasses sockets open across it.
reload_caddy() {
  if [ -n "$(compose ps -q caddy 2>/dev/null)" ]; then
    compose exec -T caddy caddy reload --config /etc/caddy/Caddyfile --adapter caddyfile
  else
    compose up -d caddy
  fi
}
