import Image from "next/image";
import type { Healthspan, HealthspanFactor, Provenance } from "@/lib/types";
// GET /api/healthspan rendered honestly: every number traces to a factor row
// with a provenance label, and nothing is extrapolated past `as_of_hh`.
const sgn=(v:number,d=1)=>`${v>=0?"+":""}${v.toFixed(d)}`;
const hhmm=(h:number)=>{const m=Math.round(h*60);return `${String(Math.floor(m/60)%24).padStart(2,"0")}:${String(m%60).padStart(2,"0")}`;};
const num=(v:number)=>String(Number(v.toFixed(2)));
const tone=(v:number)=>v>=0?"text-emerald-300":"text-rose-300";
const PROV:Record<Provenance,string>={live:"text-emerald-300",seeded:"text-violet-300",derived:"text-sky-300",missing:"text-zinc-500"};
const STATUS={on_track:"text-emerald-300",at_risk:"text-amber-300",behind:"text-rose-300"};
const KIND={tonight:"text-amber-300",today:"text-emerald-300",week:"text-sky-300",lever:"text-violet-300",you:"text-cyan-300"};
const LAYERS=["Movement","Sleep","Light & clock","Social","Environment","Diet & substances","Recovery"];
const Title=({children}:{children:string})=><p className="mt-4 mb-2 text-[10px] font-black uppercase tracking-[.2em] text-zinc-500">{children}</p>;
export function HealthspanPanel({data}:{data?:Healthspan}) {
 if(!data)return <section className="panel h-96 animate-pulse"/>;
 const {as_of_hh,hours_today,hours_ci,years_delta,years_ci,measured,layers,forecast,levers,levers_free,insights,ledger,pins,factors}=data;
 const byLayer=factors.reduce<Record<string,HealthspanFactor[]>>((all,f)=>{(all[f.layer]??=[]).push(f);return all;},{});
 const behind=ledger.filter(l=>l.status!=="on_track").sort((a,b)=>b.deficit-a.deficit), onTrack=ledger.length-behind.length;
 const counts=factors.reduce<Record<Provenance,number>>((n,f)=>{n[f.provenance]+=1;return n;},{live:0,seeded:0,derived:0,missing:0});
 return <section className="panel p-4">
  <div className="mb-2 flex items-end justify-between gap-3"><div><p className="eyebrow">{as_of_hh!==null?"Healthspan · so far today":"Healthspan"}</p><p className="text-4xl font-black text-white">{data.overall}<span className="text-sm text-zinc-500"> / 100</span></p></div><div className="flex flex-col items-end gap-1"><span className="muted">{as_of_hh!==null?`as of ${hhmm(as_of_hh)}`:data.day}</span><div className="flex gap-4"><div className="stat"><span>HOURS TODAY</span><strong className={tone(hours_today)}>{sgn(hours_today)} h <small className="muted">± {((hours_ci[1]-hours_ci[0])/2).toFixed(1)}</small></strong></div><div className="stat"><span>LIFE EXPECTANCY</span><strong className={tone(years_delta)}>{sgn(years_delta)} y <small className="muted">[{sgn(years_ci[0])}, {sgn(years_ci[1])}]</small></strong></div></div></div></div>
  <p className="muted mb-3">{measured.count} / {measured.total} measured</p>
  <div className="space-y-1.5">{LAYERS.map(name=>{const v=layers[name]??0,rows=(byLayer[name]??[]).filter(f=>f.measured);return <div key={name} title={rows.length?rows.map(f=>`${f.label} ${sgn(f.hours,2)} h`).join(" · "):"nothing measured"} className="flex items-center gap-2"><span className="w-28 truncate text-[10px] text-zinc-400">{name}</span><div className="h-1.5 flex-1 overflow-hidden rounded bg-zinc-800"><div className={`h-full ${v/100<.4?"bg-rose-500":v/100<.7?"bg-amber-400":"bg-emerald-400"}`} style={{width:`${v}%`}}/></div><span className="w-8 text-right text-[10px] text-zinc-500">{v}</span></div>;})}</div>
  <Title>Tonight</Title>{forecast.drivers.length?<div><p className="text-xs text-zinc-200">~{forecast.sleep_hours.toFixed(1)} h · HRV {sgn(forecast.hrv_change_pct,0)}% · SRI {sgn(forecast.sri_change_pts,0)} · clock +{forecast.melatonin_delay_min.toFixed(0)} min</p><div className="mt-1 flex flex-wrap gap-1">{forecast.drivers.map(d=><span key={d} className="badge text-amber-300">{d}</span>)}</div></div>:<p className="muted">no leading indicators seen yet</p>}
  <Title>Levers</Title><div className="space-y-1.5">{levers.slice(0,3).map(l=><div key={l.key} title={l.source} className="rounded-md border border-white/5 bg-white/[.025] p-2 text-xs"><div className="flex items-center gap-2"><b className="min-w-0 flex-1 truncate text-zinc-200">{l.action}</b><span className="badge">{l.time_min} min</span></div><p className="mt-1 text-[10px]"><span className="text-emerald-300">+{l.hours_gain.toFixed(1)} h</span> <span className="muted">{(l.roi_hours_per_min*60).toFixed(1)} h/h</span></p></div>)}</div>{levers_free.length>0&&<div className="mt-2 flex flex-wrap items-center gap-1"><span className="muted">costs no time</span>{levers_free.map(l=><span key={l.key} title={l.source} className="badge text-emerald-300">{l.label} +{l.hours_gain.toFixed(1)} h</span>)}</div>}
  <Title>Insights</Title><div className="space-y-1.5">{insights.map((i,n)=><p key={n} title={i.source} className="flex items-start gap-2 text-xs leading-5 text-zinc-300"><span className={`badge mt-1 shrink-0 ${KIND[i.kind]}`}>{i.kind}</span><span>{i.text}</span></p>)}</div>
  <Title>Week</Title><div className="space-y-1">{behind.map(l=><div key={l.key} className="flex items-center gap-2 text-xs"><b className="min-w-0 flex-1 truncate text-zinc-200">{l.label}</b><span className="text-[10px] text-zinc-400">{num(l.accrued)}/{num(l.target)} → {num(l.projected)}</span><span className={`badge ${STATUS[l.status]}`}>{l.status.replace("_"," ")}</span><span className="w-8 text-right text-[10px] text-zinc-500">{l.days_elapsed}/7 d</span></div>)}{onTrack>0&&<p className="muted">{onTrack} on track</p>}</div>
  <Title>Evidence</Title><div className="space-y-1">{pins.slice(-4).map((p,n)=><div key={`${p.time}-${n}`} className="flex items-start gap-2 text-xs"><span className="w-10 shrink-0 text-[10px] text-zinc-500">{p.time}</span>{p.img!==null&&<Image src={p.img} alt="" width={32} height={32} unoptimized className="h-8 w-8 rounded object-cover"/>}<span className={`min-w-0 flex-1 ${p.kind==="credit"?"text-emerald-300":"text-rose-300"}`}>{p.seen} <span className="text-zinc-400">— {p.effect}</span></span><span className="badge">{p.grade}</span></div>)}{pins.length===0&&<p className="muted">no episodes yet today</p>}</div>
  <details className="mt-3"><summary className="section-title cursor-pointer"><span>{factors.length} factors · provenance</span><span className="muted">expand</span></summary><div className="space-y-1">{factors.map(f=><div key={f.key} title={f.detail} className="flex items-center gap-2 text-xs"><b className="min-w-0 flex-1 truncate text-zinc-200">{f.label}</b><span className="text-[10px] text-zinc-400">{f.dose===null?"—":num(f.dose)}</span><span className={`w-14 text-right text-[10px] ${tone(f.hours)}`}>{sgn(f.hours,2)} h</span><span className={`badge ${PROV[f.provenance]}`}>{f.provenance==="missing"?"unmeasured":f.provenance}</span></div>)}</div></details>
  <p className="muted mt-3">live {counts.live} · seeded {counts.seeded} · derived {counts.derived} · <span className={counts.missing>0?"text-rose-300":""}>missing {counts.missing}</span></p>
 </section>;
}
