"use client";
import { api } from "@/lib/api";
import type { Tick } from "@/lib/types";
import { usePoll } from "@/lib/usePoll";
const colors:Record<string,string>={office:"bg-indigo-500",restaurant:"bg-orange-500",street:"bg-slate-500",park:"bg-emerald-500",trail:"bg-emerald-600",gym:"bg-fuchsia-500",sauna:"bg-red-500",cold_plunge:"bg-cyan-500"};
// The strip is one cell per tick, so its span in seconds depends on the capture
// cadence -- 1.5 s off Person A's glasses, not the 1 Hz SPEC §2.1 describes.
// Polled slowly: the cadence is configuration, it does not change mid-run.
export function TickStrip({ticks=[]}:{ticks?:Tick[]}) {const status=usePoll(api.status,30000);const interval=status.data?.tick_interval_s??1;const recent=ticks.slice(-30),current=recent.at(-1);return <section className="panel p-4"><div className="section-title"><span>Live ticks</span><span className="muted">{(1/interval).toFixed(2)} Hz · last {Math.round(recent.length*interval)}s</span></div><div className="flex gap-1">{recent.map(t=>{const a=t.ai;const marks=a?[a.food_present&&"F",a.screen_present&&"S",a.people_present&&"P",a.caffeine_visible&&"C",a.alcohol_visible&&"A"].filter(Boolean).join(""):"";return <div title={`${t.tick_id}: ${a?.scene??"AI unavailable"}`} key={t.tick_id} className={`flex h-9 min-w-0 flex-1 items-center justify-center rounded-sm text-[9px] font-black ${a?(colors[a.scene]??"bg-sky-600"):"bg-zinc-700 text-zinc-400"}`}>{a?marks||"·":"×"}</div>})}</div>{current&&<div className="mt-3 flex flex-wrap gap-x-5 gap-y-1 text-xs text-zinc-300"><b className="text-white">{current.tick_id}</b><span>scene <em>{current.ai?.scene??"—"}</em></span><span>activity <em>{current.ai?.activity??"—"}</em></span><span>lux proxy <em>{current.sensor.lux_proxy}</em></span><span>flow <em>{current.sensor.flow_mag.toFixed(2)}</em></span><span>AI age <em>{current.ai?`${current.ai.age_ms} ms`:"missing"}</em></span></div>}</section>}
