// The questions, in order. Every list here is meant to fit anyone, not one kind of life:
// students, desk workers, people on their feet, carers, founders, retirees. Multi-choice
// questions take any number of picks. Bryan's voice questions shape wording and timing
// only; the standard he holds the wearer to (PersonaComposer's closing lines) does not move.
extension PersonaQuestion {
    static let all: [PersonaQuestion] = [
        PersonaQuestion(id: "pronouns", prompt: "How should Bryan refer to you?", detail: nil,
                        options: [PersonaOption(id: "he", label: "He / him"),
                                  PersonaOption(id: "she", label: "She / her"),
                                  PersonaOption(id: "they", label: "They / them"),
                                  PersonaOption(id: "other", label: "Something else")],
                        maxPicks: 1, exclusiveOptionID: nil,
                        freeTextOptionID: "other", freeTextPlaceholder: "Your pronouns, e.g. ze / zir"),
        PersonaQuestion(id: "days", prompt: "What fills most of your day?", detail: "Pick everything that applies.",
                        options: [PersonaOption(id: "student", label: "Classes and studying"),
                                  PersonaOption(id: "desk", label: "Desk or laptop work"),
                                  PersonaOption(id: "meetings", label: "Meetings and calls"),
                                  PersonaOption(id: "feet", label: "On my feet: clinic, shop, site, kitchen"),
                                  PersonaOption(id: "physical", label: "Physical or outdoor work"),
                                  PersonaOption(id: "driving", label: "Driving or commuting"),
                                  PersonaOption(id: "care", label: "Looking after kids or family"),
                                  PersonaOption(id: "creative", label: "Creative or studio work"),
                                  PersonaOption(id: "travel", label: "Travelling often"),
                                  PersonaOption(id: "home", label: "Mostly at home"),
                                  PersonaOption(id: "mixed", label: "It changes day to day")],
                        maxPicks: 0, exclusiveOptionID: nil),
        PersonaQuestion(id: "goals", prompt: "What do you want help with?", detail: "Pick everything that applies.",
                        options: [PersonaOption(id: "sleep", label: "Sleep at a consistent time"),
                                  PersonaOption(id: "daylight", label: "Get outside early in the day"),
                                  PersonaOption(id: "meals", label: "Eat real meals at regular times"),
                                  PersonaOption(id: "move", label: "Move more or keep training"),
                                  PersonaOption(id: "sitting", label: "Break up long stretches of sitting or screens"),
                                  PersonaOption(id: "cut", label: "Cut back on something"),
                                  PersonaOption(id: "phone", label: "Less phone when it isn't helping"),
                                  PersonaOption(id: "people", label: "More time with people"),
                                  PersonaOption(id: "stress", label: "Wind down and handle stress"),
                                  PersonaOption(id: "water", label: "Drink more water"),
                                  PersonaOption(id: "routine", label: "Keep habits on busy or travel days"),
                                  PersonaOption(id: "meds", label: "Take medication or supplements on time"),
                                  PersonaOption(id: "notsure", label: "Not sure yet, let Bryan watch first")],
                        maxPicks: 0, exclusiveOptionID: "notsure"),
        PersonaQuestion(id: "bedtime", prompt: "When do you usually fall asleep?", detail: nil,
                        options: [PersonaOption(id: "early", label: "Before 11 pm"),
                                  PersonaOption(id: "late", label: "11 pm to 1 am"),
                                  PersonaOption(id: "verylate", label: "After 1 am"),
                                  PersonaOption(id: "shift", label: "I work nights or shifts"),
                                  PersonaOption(id: "varies", label: "It varies a lot")],
                        maxPicks: 1, exclusiveOptionID: nil),
        PersonaQuestion(id: "training", prompt: "How much do you move in a week?", detail: nil,
                        options: [PersonaOption(id: "none", label: "Not much right now"),
                                  PersonaOption(id: "casual", label: "I move when I can"),
                                  PersonaOption(id: "routine", label: "A regular routine"),
                                  PersonaOption(id: "event", label: "Training for a race, sport or event"),
                                  PersonaOption(id: "rehab", label: "Getting back into it after a break or injury")],
                        maxPicks: 1, exclusiveOptionID: nil),
        PersonaQuestion(id: "food", prompt: "How do you usually eat?", detail: nil,
                        options: [PersonaOption(id: "regular", label: "Regular meals"),
                                  PersonaOption(id: "cook", label: "I cook most of my meals"),
                                  PersonaOption(id: "out", label: "Mostly eating out or delivery"),
                                  PersonaOption(id: "skip", label: "I skip meals when busy"),
                                  PersonaOption(id: "desk", label: "Snacks more than meals"),
                                  PersonaOption(id: "night", label: "Mostly late at night")],
                        maxPicks: 1, exclusiveOptionID: nil),
        PersonaQuestion(id: "caffeine", prompt: "What about caffeine?", detail: nil,
                        options: [PersonaOption(id: "none", label: "I don't drink it"),
                                  PersonaOption(id: "keep", label: "Keep it as is"),
                                  PersonaOption(id: "less", label: "Help me drink less"),
                                  PersonaOption(id: "noon", label: "None after noon"),
                                  PersonaOption(id: "track", label: "Not sure, track it first")],
                        maxPicks: 1, exclusiveOptionID: nil),
        PersonaQuestion(id: "cut", prompt: "Anything else you want to cut back on?", detail: "Pick any.",
                        options: [PersonaOption(id: "alcohol", label: "Alcohol"),
                                  PersonaOption(id: "nicotine", label: "Nicotine"),
                                  PersonaOption(id: "weed", label: "Weed"),
                                  PersonaOption(id: "sugar", label: "Sugar and junk food"),
                                  PersonaOption(id: "energy", label: "Energy drinks"),
                                  PersonaOption(id: "screens", label: "Late-night screens"),
                                  PersonaOption(id: "nothing", label: "Nothing")],
                        maxPicks: 0, exclusiveOptionID: "nothing"),
        PersonaQuestion(id: "frequency", prompt: "How often should Bryan speak up?", detail: nil,
                        options: [PersonaOption(id: "patterns", label: "Rarely, only when a pattern forms over days"),
                                  PersonaOption(id: "daily", label: "Once or twice a day, the things that matter most"),
                                  PersonaOption(id: "moments", label: "At the moments that matter, as they happen"),
                                  PersonaOption(id: "often", label: "Often, hold me to it"),
                                  PersonaOption(id: "every", label: "Every time you spot something")],
                        maxPicks: 1, exclusiveOptionID: nil),
        PersonaQuestion(id: "quiet", prompt: "When should Bryan stay quiet?", detail: "Pick any.",
                        options: [PersonaOption(id: "morning", label: "First thing in the morning"),
                                  PersonaOption(id: "work", label: "During work or class hours"),
                                  PersonaOption(id: "meals", label: "During meals"),
                                  PersonaOption(id: "driving", label: "While I'm driving"),
                                  PersonaOption(id: "evening", label: "Late in the evening"),
                                  PersonaOption(id: "never", label: "No quiet times")],
                        maxPicks: 0, exclusiveOptionID: "never"),
        PersonaQuestion(id: "tone", prompt: "How should Bryan talk to you?", detail: nil,
                        options: [PersonaOption(id: "dry", label: "Short and dry"),
                                  PersonaOption(id: "warm", label: "Warm and encouraging"),
                                  PersonaOption(id: "blunt", label: "Blunt, no sugarcoating"),
                                  PersonaOption(id: "coach", label: "Like a coach: specific and practical"),
                                  PersonaOption(id: "curious", label: "Ask me before telling me"),
                                  PersonaOption(id: "light", label: "Light, with some humour")],
                        maxPicks: 1, exclusiveOptionID: nil),
        PersonaQuestion(id: "people", prompt: "When you're with other people, Bryan should…", detail: nil,
                        options: [PersonaOption(id: "silent", label: "Stay silent"),
                                  PersonaOption(id: "matters", label: "Speak only if it matters"),
                                  PersonaOption(id: "brief", label: "Keep it to a few words"),
                                  PersonaOption(id: "noask", label: "Never ask me questions, just tell me")],
                        maxPicks: 1, exclusiveOptionID: nil),
    ]
}
