extension PersonaQuestion {
    static let all: [PersonaQuestion] = [
        PersonaQuestion(id: "pronouns", prompt: "How should Bryan refer to you?", detail: nil,
                        options: [PersonaOption(id: "he", label: "He / him"),
                                  PersonaOption(id: "she", label: "She / her"),
                                  PersonaOption(id: "they", label: "They / them")],
                        maxPicks: 1, exclusiveOptionID: nil),
        PersonaQuestion(id: "days", prompt: "What fills most of your day?", detail: nil,
                        options: [PersonaOption(id: "student", label: "Classes and studying"),
                                  PersonaOption(id: "desk", label: "Desk or laptop work"),
                                  PersonaOption(id: "feet", label: "On my feet"),
                                  PersonaOption(id: "mixed", label: "A mix of everything")],
                        maxPicks: 1, exclusiveOptionID: nil),
        PersonaQuestion(id: "goals", prompt: "What do you want help with?", detail: "Pick up to three.",
                        options: [PersonaOption(id: "sleep", label: "Sleep at a consistent time"),
                                  PersonaOption(id: "daylight", label: "Get daylight before noon"),
                                  PersonaOption(id: "meals", label: "Eat real meals"),
                                  PersonaOption(id: "move", label: "Move more or train"),
                                  PersonaOption(id: "cut", label: "Cut back on something"),
                                  PersonaOption(id: "phone", label: "Less phone while working"),
                                  PersonaOption(id: "people", label: "More time with people")],
                        maxPicks: 3, exclusiveOptionID: nil),
        PersonaQuestion(id: "bedtime", prompt: "When do you usually fall asleep?", detail: nil,
                        options: [PersonaOption(id: "early", label: "Before 11 pm"),
                                  PersonaOption(id: "late", label: "11 pm to 1 am"),
                                  PersonaOption(id: "verylate", label: "1 to 3 am"),
                                  PersonaOption(id: "varies", label: "It varies a lot")],
                        maxPicks: 1, exclusiveOptionID: nil),
        PersonaQuestion(id: "training", prompt: "Are you training for anything?", detail: nil,
                        options: [PersonaOption(id: "none", label: "No"),
                                  PersonaOption(id: "casual", label: "I work out casually"),
                                  PersonaOption(id: "event", label: "A race or event")],
                        maxPicks: 1, exclusiveOptionID: nil),
        PersonaQuestion(id: "food", prompt: "How do you usually eat?", detail: nil,
                        options: [PersonaOption(id: "regular", label: "Regular meals"),
                                  PersonaOption(id: "skip", label: "I skip meals when busy"),
                                  PersonaOption(id: "desk", label: "Snacks at my desk"),
                                  PersonaOption(id: "night", label: "Mostly late at night")],
                        maxPicks: 1, exclusiveOptionID: nil),
        PersonaQuestion(id: "caffeine", prompt: "What about caffeine?", detail: nil,
                        options: [PersonaOption(id: "none", label: "I don't drink it"),
                                  PersonaOption(id: "keep", label: "Keep it as is"),
                                  PersonaOption(id: "less", label: "Help me drink less"),
                                  PersonaOption(id: "noon", label: "None after noon")],
                        maxPicks: 1, exclusiveOptionID: nil),
        PersonaQuestion(id: "cut", prompt: "Anything else you want to cut back on?", detail: "Pick any.",
                        options: [PersonaOption(id: "alcohol", label: "Alcohol"),
                                  PersonaOption(id: "nicotine", label: "Nicotine"),
                                  PersonaOption(id: "weed", label: "Weed"),
                                  PersonaOption(id: "sugar", label: "Sugar and junk food"),
                                  PersonaOption(id: "nothing", label: "Nothing")],
                        maxPicks: 5, exclusiveOptionID: "nothing"),
        PersonaQuestion(id: "frequency", prompt: "How often should Bryan speak up?", detail: nil,
                        options: [PersonaOption(id: "rarely", label: "Rarely, only when a pattern forms"),
                                  PersonaOption(id: "moments", label: "At the moments that matter"),
                                  PersonaOption(id: "often", label: "Often, hold me to it")],
                        maxPicks: 1, exclusiveOptionID: nil),
        PersonaQuestion(id: "tone", prompt: "How should Bryan talk to you?", detail: nil,
                        options: [PersonaOption(id: "dry", label: "Short and dry"),
                                  PersonaOption(id: "warm", label: "Warm and encouraging"),
                                  PersonaOption(id: "blunt", label: "Blunt, no sugarcoating")],
                        maxPicks: 1, exclusiveOptionID: nil),
        PersonaQuestion(id: "people", prompt: "When you're with other people, Bryan should…", detail: nil,
                        options: [PersonaOption(id: "silent", label: "Stay silent"),
                                  PersonaOption(id: "matters", label: "Speak only if it matters")],
                        maxPicks: 1, exclusiveOptionID: nil),
    ]
}
